DROP TABLE IF EXISTS "BACKUP";
CREATE TABLE "BACKUP" ("BAC_NUM" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "BAC_URL" VARCHAR, "BAC_NAME" VARCHAR, "BAC_VAR_YEAR" VARCHAR, "BAC_VAR_MOTH" VARCHAR, "BAC_EXTENSION" VARCHAR);
DROP TABLE IF EXISTS "LOG";
CREATE TABLE "LOG" ("LOG_NUM" INTEGER PRIMARY KEY  NOT NULL ,"BAC_NUM" INTEGER DEFAULT (null) ,"LOG_SUCCESSFUL" BOOL,"LOG_FILE_NAME" VARCHAR,"LOG_TIME_VERIFICATION" DATETIME);
